apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: wil42/playground:v2
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: nginx
  type: ClusterIP
