apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.8
        name: hello-k8s
        env:
        - name: MESSAGE
          value: Hello from app