apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: playground
  name: playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - image: wil42/playground:v2
        name: playground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: playground
  name: playground
  namespace: dev
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: playground
  type: ClusterIP
